# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945c9dfe51b0de00cd63c4cc74ffdf6c6e54af57b0fb60c904144f47c20b10299a75256f38d8d02923865ca14c404c6d3a7a11f8b2b90f470d34ce09f814ce0f

test:
  secret_key_base: 630fc532488ef1522dd59258de99143122baf200e37193b722cd4d46beed37ad5d8471bfa4d2fbabaf3fb420620db088f356b5786e7af27be0f0eb3b3d7c281f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
